"""
build_canonical.py — writes data/canonical_titles.json from embedded literary knowledge.

Each key is the EXACT author name as stored in the dataset.
Each value is a list of canonical / widely-anthologized titles for that author,
in the form most likely to appear in this dataset.

Dickinson : first-line titles (dataset wraps them in "double quotes" + Title Case;
            the curate script strips quotes before fuzzy-matching)
Shakespeare: "The Sonnets [ROMAN] - [first line]"  — dataset's exact pattern
Petrarch   : "Sonnet [ROMAN]."  (with trailing period, Roman numerals)
Pessoa     : "Sonnet [ROMAN]."  (same pattern, I–XXXV are all his English Sonnets)
Masters    : character names from Spoon River Anthology
"""

import json, os

CANONICAL = {

"William Wordsworth": [
    "I Wandered Lonely as a Cloud",
    "Lines Written in Early Spring",
    "Tintern Abbey",
    "Lines Composed a Few Miles above Tintern Abbey",
    "London, 1802",
    "Composed upon Westminster Bridge, September 3, 1802",
    "The World Is Too Much with Us",
    "Nutting",
    "Resolution and Independence",
    "Ode: Intimations of Immortality",
    "She Dwelt among the Untrodden Ways",
    "A Slumber Did My Spirit Seal",
    "Strange Fits of Passion Have I Known",
    "Three Years She Grew in Sun and Shower",
    "Lucy Gray",
    "To a Butterfly",
    "My Heart Leaps Up",
    "To the Cuckoo",
    "Stepping Westward",
    "The Solitary Reaper",
    "Surprised by Joy",
    "It Is a Beauteous Evening, Calm and Free",
],

"Thomas Hardy": [
    "The Darkling Thrush",
    "Afterwards",
    "Neutral Tones",
    "The Voice",
    "During Wind and Rain",
    "The Convergence of the Twain",
    "Hap",
    "In Time of 'The Breaking of Nations'",
    "The Oxen",
    "Channel Firing",
    "Drummer Hodge",
    "A Broken Appointment",
    "I Look Into My Glass",
    "Ah, Are You Digging on My Grave?",
    "When I Set Out for Lyonnesse",
    "The Man He Killed",
    "In Tenebris",
    "The Going",
    "At Castle Boterel",
    "The Self-Unseeing",
    "Weathers",
],

"Robert Burns": [
    # Dataset uses full descriptive titles for the famous poems:
    "To A Mouse, On Turning Her Up In Her Nest With The Plough, November, 1785",
    "To A Louse, On Seeing One In A Lady's Bonnet, At Church",
    "A Red, Red Rose",
    "The Red, Red Rose",    # dataset has both "A" and "The" variants
    "Auld Lang Syne",
    "John Anderson",        # dataset drops "My Jo"
    "John Anderson My Jo",
    "Flow Gently, Sweet Afton",
    "Mary Morison",
    "To A Haggis",          # dataset uses "To" not "Address to"
    "Address to a Haggis",
    "Of A' The Airts The Wind Can Blaw",
    "Is There, For Honest Poverty",
    "Is There for Honest Poverty",
    "Ae Fond Kiss",
    "Green Grow the Rashes",
    "Coming Through The Rye",
    "My Heart's In The Highlands",
    "Scots Wha Hae",
    "Highland Mary",
    "A Man's A Man For A' That",
    "Tam o' Shanter",
],

"Emily Elizabeth Dickinson": [
    "Because I could not stop for Death",
    "I heard a Fly buzz - when I died",
    "Hope is the thing with feathers",
    "I'm Nobody! Who are you?",
    "Tell all the truth but tell it slant",
    "After great pain, a formal feeling comes",
    "Success is counted sweetest",
    "This is my letter to the World",
    "A narrow Fellow in the Grass",
    "Safe in their Alabaster Chambers",
    "Much Madness is Divinest Sense",
    "I dwell in Possibility",
    "There's a certain Slant of light",
    "Wild Nights - Wild Nights!",
    "The Brain - is wider than the Sky",
    "I died for Beauty - but was scarce",
    "I felt a Funeral, in my Brain",
    "The Soul selects her own Society",
    "One need not be a Chamber - to be Haunted",
    "I taste a liquor never brewed",
    "I'm Nobody! Who are you?",
    "God is a distant - stately Lover",
    "Pain - has an Element of Blank",
    "Because I could not stop for Death",
    "I heard a Fly buzz",
    "If I can stop one Heart from breaking",
    "The Bustle in a House",
],

"Paul Laurence Dunbar": [
    "We Wear the Mask",
    "Sympathy",
    "When Malindy Sings",
    "The Haunted Oak",
    "A Death Song",
    "Little Brown Baby",
    "Ode to Ethiopia",
    "The Colored Soldiers",
    "Life",
    "Ships That Pass in the Night",
    "Dawn",
    "The Debt",
    "Ere Sleep Comes Down to Soothe the Weary Eyes",
    "The Party",
    "Accountability",
    "A Song",
    "The Poet",
    "After the Quarrel",
    "The Lawyers' Ways",
],

"John Clare": [
    "I Am",
    "Badger",
    "The Nightingale's Nest",
    "Clock-a-Clay",
    "First Love",
    "Autumn",
    "Snow Storm",
    "An Invite to Eternity",
    "Remembrance",
    "Love Lives Beyond the Tomb",
    "Song",
    "The Yellowhammer's Nest",
    "Pastoral Poesy",
    "The Peasant Poet",
    "To Mary",
    "A Vision",
    "Sudden Shower",
    "The Frightened Ploughman",
],

"William Butler Yeats": [
    "The Second Coming",
    "Sailing to Byzantium",
    "The Lake Isle of Innisfree",
    "Among School Children",
    "Easter, 1916",
    "When You Are Old",
    "The Wild Swans at Coole",
    "Leda and the Swan",
    "No Second Troy",
    "Adam's Curse",
    "The Circus Animals' Desertion",
    "A Prayer for My Daughter",
    "An Irish Airman Foresees His Death",
    "He Wishes for the Cloths of Heaven",
    "Down by the Salley Gardens",
    "Who Goes with Fergus?",
    "The Rose of the World",
    "The Song of Wandering Aengus",
    "Byzantium",
    "Under Ben Bulben",
    "Politics",
    "The Stolen Child",
    "A Coat",
    "The Fascination of What's Difficult",
    "The Municipal Gallery Revisited",
],

"Francesco Petrarca (Petrarch)": [
    "Sonnet I.",
    "Sonnet III.",
    "Sonnet XVI.",
    "Sonnet XXXV.",
    "Sonnet XLVII.",
    "Sonnet LXI.",
    "Sonnet LXII.",
    "Sonnet XC.",
    "Sonnet XCIV.",
    "Sonnet CIV.",
    "Sonnet CXXVI.",
    "Sonnet CXXXII.",
    "Sonnet CXXXIV.",
    "Sonnet CLXXXIX.",
    "Sonnet CCXCII.",
    "Sonnet CCCXI.",
    "Sonnet CCCXXXIII.",
    "Canzone CXXVI.",
    "Ballata I.",
    "Sestina I.",
],

"Johann Wolfgang von Goethe": [
    "Wanderer's Night Song",
    "Wanderers Nachtlied",
    "The Erl-King",
    "Erlking",
    "Mignon's Song",
    "Knowest Thou the Land",
    "Prometheus",
    "Ganymede",
    "To the Moon",
    "Welcome and Farewell",
    "The Sorcerer's Apprentice",
    "May Song",
    "Nearness of the Beloved",
    "Holy Longing",
    "Found",
    "The Fisherman",
    "Dedication",
    "Restless Love",
],

"Walt Whitman": [
    "O Captain! My Captain!",
    "When Lilacs Last in the Dooryard Bloom'd",
    "I Sing the Body Electric",
    "Out of the Cradle Endlessly Rocking",
    "Crossing Brooklyn Ferry",
    "When I Heard the Learn'd Astronomer",
    "A Noiseless Patient Spider",
    "The Wound-Dresser",
    "Beat! Beat! Drums!",
    "Vigil Strange I Kept on the Field One Night",
    "Bivouac on a Mountain Side",
    "To a Locomotive in Winter",
    "Give Me the Splendid Silent Sun",
    "There Was a Child Went Forth",
    "Reconciliation",
    "To You",
    "Beginning My Studies",
    "A Farm Picture",
    "The Runner",
    "Song of Myself",
    "Sparkles from the Wheel",
    "Had I the Choice",
],

"Percy Bysshe Shelley": [
    "Ode to the West Wind",
    "Ozymandias",
    "To a Skylark",
    "Hymn to Intellectual Beauty",
    "Mutability",
    "England in 1819",
    "The Cloud",
    "Love's Philosophy",
    "When the lamp is shattered",
    "Music, when soft voices die",
    "Stanzas Written in Dejection, Near Naples",
    "To Night",
    "The Indian Serenade",
    "Song to the Men of England",
    "Adonais",
    "Lines Written Among the Euganean Hills",
    "A Lament",
    "A Dirge",
    "Good-Night",
    "A Song",
],

"Alfred Lord Tennyson": [
    "The Charge of the Light Brigade",
    "Ulysses",
    "Crossing the Bar",
    "Tithonus",
    "Break, Break, Break",
    "Mariana",
    "Tears, Idle Tears",
    "Now Sleeps the Crimson Petal",
    "The Eagle",
    "Sweet and Low",
    "Flower in the Crannied Wall",
    "Come Not When I Am Dead",
    "The Lady of Shalott",
    "The Lotus-Eaters",
    "Locksley Hall",
    "All Things Will Die",
    "The Splendour Falls",
    "Ask Me No More",
    "Morte D'Arthur",
    "Ring Out, Wild Bells",
],

"Christina Georgina Rossetti": [
    "Remember",
    "Song",
    "A Birthday",
    "Up-Hill",
    "In the Bleak Midwinter",
    "Goblin Market",
    "Echo",
    "No Thank You, John",
    "A Better Resurrection",
    "Amor Mundi",
    "Twice",
    "Spring",
    "Winter Rain",
    "When I am dead, my dearest",
    "The Convent Threshold",
    "Dream Land",
    "Who Has Seen the Wind?",
    "Passing Away",
    "Does the road wind up-hill all the way?",
    "A Christmas Carol",
],

"Charles Baudelaire": [
    "Correspondences",
    "Correspondances",
    "Invitation to the Voyage",
    "The Albatross",
    "A Carcass",
    "A Rotting Carcase",
    "Beauty",
    "Meditation",
    "Recueillement",
    "The Voyage",
    "Exotic Perfume",
    "The Head of Hair",
    "The Balcony",
    "Benediction",
    "To the Reader",
    "Au Lecteur",
    "Spleen",
    "Autumn Song",
    "The Cat",
    "Cats",
    "Hymn to Beauty",
    "Elevation",
    "The Ideal",
    "Reversibility",
    "Moesta et Errabunda",
],

"Robert Browning": [
    "My Last Duchess",
    "The Pied Piper of Hamelin",
    "Fra Lippo Lippi",
    "Andrea del Sarto",
    "Porphyria's Lover",
    "Childe Roland to the Dark Tower Came",
    "Rabbi Ben Ezra",
    "Home-Thoughts, from Abroad",
    "Home-Thoughts, from the Sea",
    "Meeting at Night",
    "Parting at Morning",
    "Love among the Ruins",
    "A Grammarian's Funeral",
    "Prospice",
    "The Bishop Orders His Tomb at Saint Praxed's Church",
    "Two in the Campagna",
    "Soliloquy of the Spanish Cloister",
    "The Lost Leader",
    "How They Brought the Good News from Ghent to Aix",
],

"Alexander Pope": [
    "Ode on Solitude",
    "The Universal Prayer",
    "Epistle to Miss Teresa Blount",
    "Epistle to Mrs Teresa Blount",
    "Elegy to the Memory of an Unfortunate Lady",
    "Eloisa to Abelard",
    "The Rape of the Lock",
    "An Essay on Man",
    "An Essay on Criticism",
    "Epistle to Dr. Arbuthnot",
    "Windsor-Forest",
    "Epistle to Burlington",
    "The Dunciad",
    "Epistle to a Lady",
    "Epistle II: To a Lady",
],

"George Gordon Byron": [
    # Many canonical Byron poems are not in this dataset (too long or absent).
    # Add forms that match what IS here, including footnote-stripped versions:
    "She Walks in Beauty",
    "When We Two Parted",
    "The Destruction of Sennacherib",
    "So We'll Go No More A-Roving",    # dataset: "So We'll Go No More A-Roving.[578]"
    "So, We'll Go No More a Roving",
    "Darkness",
    "Written After Swimming From Sestos To Abydos",
    "Fare Thee Well",
    "On This Day I Complete My Thirty-Sixth Year",
    "Maid of Athens, Ere We Part",
    "Remember Thee! Remember Thee!",
    "Stanzas for Music",
    "Lines Written in an Album",
    "Lachin Y Gair",
    "Stanzas Written On The Road Between Florence And Pisa",
    "Churchill's Grave",
    "Sonnet On Chillon",
    "There Be None of Beauty's Daughters",
    "Remembrance",
],

"Victor-Marie Hugo": [
    "Tomorrow, at Dawn",
    "Demain, des l'aube",
    "Oceano Nox",
    "Boaz Asleep",
    "Veni, Vidi, Vixi",
    "Tristesse d'Olympio",
    "The Djinns",
    "Les Djinns",
    "Saison des Semailles",
    "A Villequier",
    "My Napoleon",
],

"Robert Lee Frost": [
    "The Road Not Taken",
    "Stopping by Woods on a Snowy Evening",
    "Mending Wall",
    "After Apple Picking",
    "After Apple-Picking",
    "Birches",
    "Fire and Ice",
    "Nothing Gold Can Stay",
    "Desert Places",
    "Acquainted with the Night",
    "Design",
    "Once by the Pacific",
    "The Oven Bird",
    "Directive",
    "The Death of the Hired Man",
    "Home Burial",
    "Out, Out",
    "A Patch of Old Snow",
    "Dust of Snow",
    "Hyla Brook",
    "The Pasture",
    "October",
    "A Late Walk",
    "The Tuft of Flowers",
],

"William Shakespeare": [
    "The Sonnets I - From fairest creatures we desire increase",
    "The Sonnets XII - When I do count the clock that tells the time",
    "The Sonnets XV - When I consider every thing that grows",
    "The Sonnets XVII - Who will believe my verse in time to come",
    "The Sonnets XVIII - Shall I compare thee to a summer's day",
    "The Sonnets XIX - Devouring Time, blunt thou the lion's paws",
    "The Sonnets XXIII - As an unperfect actor on the stage",
    "The Sonnets XXIX - When, in disgrace with fortune and men's eyes",
    "The Sonnets XXX - When to the sessions of sweet silent thought",
    "The Sonnets XXXIII - Full many a glorious morning have I seen",
    "The Sonnets LV - Not marble nor the gilded monuments",
    "The Sonnets LX - Like as the waves make towards the pebbled shore",
    "The Sonnets LXIV - When I have seen by Time's fell hand defaced",
    "The Sonnets LXV - Since brass, nor stone, nor earth, nor boundless sea",
    "The Sonnets LXVI - Tired with all these, for restful death I cry",
    "The Sonnets LXXI - No longer mourn for me when I am dead",
    "The Sonnets LXXIII - That time of year thou mayst in me behold",
    "The Sonnets XCIV - They that have power to hurt, and will do none",
    "The Sonnets XCVII - How like a winter hath my absence been",
    "The Sonnets XCVIII - From you have I been absent in the spring",
    "The Sonnets CIV - To me, fair friend, you never can be old",
    "The Sonnets CVI - When in the chronicle of wasted time",
    "The Sonnets CVII - Not mine own fears, nor the prophetic soul",
    "The Sonnets CXVI - Let me not to the marriage of true minds",
    "The Sonnets CXXI - 'Tis better to be vile than vile esteemed",
    "The Sonnets CXXIX - The expense of spirit in a waste of shame",
    "The Sonnets CXXX - My mistress' eyes are nothing like the sun",
    "The Sonnets CXXXVIII - When my love swears that she is made of truth",
    "The Sonnets CXLIV - Two loves I have of comfort and despair",
],

"John Keats": [
    "Ode to a Nightingale",
    "Ode on a Grecian Urn",
    "Ode on Melancholy",
    "To Autumn",
    "La Belle Dame sans Merci",
    "Bright Star",
    "On First Looking into Chapman's Homer",
    "Ode to Psyche",
    "When I Have Fears That I May Cease to Be",
    "To Sleep",
    "This Living Hand",
    "The Eve of St. Agnes",
    "Lamia",
    "Isabella; or, The Pot of Basil",
    "Hyperion",
    "Endymion",
    "Sleep and Poetry",
    "Lines on the Mermaid Tavern",
    "Robin Hood",
    "Fancy",
],

"William Blake": [
    "The Tyger",
    "The Lamb",
    "London",
    "And Did Those Feet in Ancient Time",
    "Jerusalem",
    "Auguries of Innocence",
    "The Garden of Love",
    "The Sick Rose",
    "A Poison Tree",
    "The Little Black Boy",
    "Infant Joy",
    "Infant Sorrow",
    "The Chimney Sweeper",
    "Holy Thursday",
    "The Clod and the Pebble",
    "Mock On Mock On Voltaire Rousseau",
    "Ah Sunflower",
    "A Cradle Song",
    "Introduction",
    "The Divine Image",
    "A Divine Image",
    "Night",
    "The Echoing Green",
    "The Tiger",
],

"John Milton": [
    "Lycidas",
    "On the Morning of Christ's Nativity",
    "How Soon Hath Time",
    "On Shakespeare",
    "L'Allegro",
    "Il Penseroso",
    "On His Blindness",
    "Sonnet XIX",
    "Sonnet XVIII",
    "When I Consider How My Light Is Spent",
    "On the Late Massacre in Piedmont",
    "To Mr. Cyriack Skinner upon his Blindness",
    "Lawrence of Virtuous Father",
    "Methought I Saw My Late Espoused Saint",
    "To a Virtuous Young Lady",
    "Paradise Lost",
],

"Oscar Fingal O'Flahertie Wills Wilde": [
    "The Ballad of Reading Gaol",
    "Impression du Matin",
    "In the Gold Room",
    "Requiescat",
    "Impression: Le Reveillon",
    "The New Remorse",
    "Helas!",
    "E Tenebris",
    "The Garden of Eros",
    "Humanitad",
    "Symphony in Yellow",
    "To My Wife",
    "Ave Imperatrix",
    "Ravenna",
    "Chanson",
    "The Sphinx",
    "Sonnet on the Sale by Auction of Keats' Love Letters",
],

"Elizabeth Barrett Browning": [
    "How do I love thee? Let me count the ways",
    "Sonnet 43",
    "Sonnets from the Portuguese: 43",
    "Sonnets from the Portuguese: I thought once how Theocritus had sung",
    "Sonnets from the Portuguese: If thou must love me",
    "Sonnets from the Portuguese: Go from me",
    "The Cry of the Children",
    "Grief",
    "To Flush, My Dog",
    "A Musical Instrument",
    "The Romance of the Swan's Nest",
    "Sonnets from the Portuguese: XIV",
    "Sonnets from the Portuguese: XXIX",
    "Sonnets from the Portuguese: VI",
    "A Year's Spinning",
    "My Heart and I",
    "Bianca among the Nightingales",
],

"Alfred Edward Housman": [
    # Dataset stores A Shropshire Lad as compound titles:
    # "Poems From "A Shropshire Lad" - [ROMAN] - [subtitle if any]"
    'Poems From "A Shropshire Lad" - I - 1887',
    'Poems From "A Shropshire Lad" - II',           # Loveliest of Trees
    'Poems From "A Shropshire Lad" - III - The Recruit',
    'Poems From "A Shropshire Lad" - IV - Reveille',
    'Poems From "A Shropshire Lad" - XIII',         # When I Was One-and-Twenty
    'Poems From "A Shropshire Lad" - XIX - To An Athlete Dying Young',
    'Poems From "A Shropshire Lad" - XXI - Bredon Hill',
    'Poems From "A Shropshire Lad" - XXIII',        # The lads in their hundreds
    'Poems From "A Shropshire Lad" - XXVII',        # Is My Team Ploughing
    'Poems From "A Shropshire Lad" - XXVIII - The Welsh Marches',
    'Poems From "A Shropshire Lad" - XXXI',         # On Wenlock Edge
    'Poems From "A Shropshire Lad" - XL',           # Into My Heart an Air That Kills
    'Poems From "A Shropshire Lad" - XLIII - The Immortal Part',
    # Last Poems and More Poems are stored without the compound prefix:
    "Epitaph On An Army Of Mercenaries",
    "Could man be drunk for ever",
    "Easter Hymn",
    "Here Dead We Lie",
    "Tell me not here, it needs not saying",
    "The laws of God, the laws of man",
],

"Dante Alighieri": [
    "Inferno, Canto I",
    "Inferno, Canto III",
    "Inferno, Canto V",
    "Purgatorio, Canto I",
    "Paradiso, Canto XXXIII",
    "The Divine Comedy",
],

"Ben Jonson": [
    "To Celia",
    "Drink to Me Only with Thine Eyes",
    "On My First Son",
    "To Penshurst",
    "Song: To Celia",
    "Hymn to Diana",
    "Epitaph on S.P.",
    "Inviting a Friend to Supper",
    "Still to Be Neat",
    "Come, My Celia",
    "On My First Daughter",
    "Her Triumph",
    "A Celebration of Charis",
    "An Ode to Himself",
    "Ode to Himself",
    "A Hymn on the Nativity of My Saviour",
    "A Hymn to God the Father",
    "A Farewell to the World",
    "An Elegy",
],

"Gerard Manley Hopkins": [
    "The Windhover",
    "God's Grandeur",
    "Pied Beauty",
    "Spring and Fall",
    "Felix Randal",
    "Inversnaid",
    "As kingfishers catch fire",
    "Hurrahing in Harvest",
    "Carrion Comfort",
    "No worst, there is none",
    "I wake and feel the fell of dark",
    "Thou art indeed just, Lord",
    "That Nature is a Heraclitean Fire",
    "The Leaden Echo and the Golden Echo",
    "Andromeda",
    "Binsey Poplars",
    "Duns Scotus's Oxford",
    "The Caged Skylark",
    "Henry Purcell",
],

"Samuel Taylor Coleridge": [
    "The Rime of the Ancient Mariner",
    "Kubla Khan",
    "Christabel",
    "Frost at Midnight",
    "Dejection: An Ode",
    "This Lime-Tree Bower My Prison",
    "The Eolian Harp",
    "Work Without Hope",
    "Youth and Age",
    "Love",
    "To Nature",
    "Phantom",
    "Fears in Solitude",
    "Hymn Before Sun-Rise",
],

"Emily Bronte": [
    "No Coward Soul Is Mine",
    "Remembrance",
    "The Prisoner",
    "I Am the Only Being Whose Doom",
    "Love and Friendship",
    "The Night-Wind",
    "Fall, Leaves, Fall",
    "To Imagination",
    "The Old Stoic",
    "Shall Earth No More Inspire Thee",
    "A Death-Scene",
    "Plead for Me",
    "Often Rebuked, Yet Always Back Returning",
    "Song",
    "Stars",
    "Light Up Thy Halls",
],

"James Joyce": [
    "I Hear an Army",
    "Strings in the Earth and Air",
    "O Sweetheart, Hear You",
    "Bid Adieu",
    "Alone",
    "A Flower Given to My Daughter",
    "She Weeps over Rahoon",
    "Simples",
    "Tutto è Sciolto",
    "Nightpiece",
    "Watching the Needleboats at San Sabba",
    "Tilly",
    "On the Beach at Fontana",
    "Flood",
    "Cabra",
    "Bahnhofstrasse",
],

"Giacomo Leopardi": [
    "The Infinite",
    "L'Infinito",
    "To Silvia",
    "A Silvia",
    "Saturday in the Village",
    "The Calm After the Storm",
    "Night Song of a Wandering Shepherd of Asia",
    "Canto Notturno",
    "To Italy",
    "To Himself",
    "A Se Stesso",
    "The Last Song of Sappho",
    "To Spring",
    "The Moon",
    "The Lonely Sparrow",
    "The Setting of the Moon",
],

"Fernando Ant'nio Nogueira Pessoa": [
    "Sonnet I.",
    "Sonnet II.",
    "Sonnet III.",
    "Sonnet IV.",
    "Sonnet V.",
    "Sonnet VI.",
    "Sonnet VII.",
    "Sonnet VIII.",
    "Sonnet IX.",
    "Sonnet X.",
    "Sonnet XI.",
    "Sonnet XII.",
    "Sonnet XIII.",
    "Sonnet XIV.",
    "Sonnet XV.",
    "Sonnet XVI.",
    "Sonnet XVII.",
    "Sonnet XVIII.",
    "Sonnet XIX.",
    "Sonnet XX.",
    "Sonnet XXI.",
    "Sonnet XXII.",
    "Sonnet XXIII.",
    "Sonnet XXIV.",
    "Sonnet XXV.",
    "Sonnet XXVI.",
    "Sonnet XXVII.",
    "Sonnet XXVIII.",
    "Sonnet XXIX.",
    "Sonnet XXX.",
    "Sonnet XXXI.",
    "Sonnet XXXII.",
    "Sonnet XXXIII.",
    "Sonnet XXXIV.",
    "Sonnet XXXV.",
],

"Bertolt Brecht": [
    "A Worker Reads History",
    "To Posterity",
    "An die Nachgeborenen",
    "Legend of the Dead Soldier",
    "Of Poor B.B.",
    "The Burning of the Books",
    "Hollywood Elegies",
    "Memory of Marie A.",
    "General, Your Tank Is a Powerful Vehicle",
    "Epitaph",
    "Contemplating Hell",
    "How Fortunate the Man with None",
    "I Want to Go with the One I Love",
    "The Moldau Song",
    "Alabama Song",
    "1940",
    "Mack the Knife",
    "Children's Crusade",
],

"Anna Akhmatova": [
    "Lot's Wife",
    "I Wrung My Hands",
    "The Grey-Eyed King",
    "Courage",
    "The Song of the Last Meeting",
    "Reading Hamlet",
    "Cleopatra",
    "The Sentence",
    "The Last Toast",
    "Boris Pasternak",
    "For Osip Mandelstam",
    "Everything",
    "Along the Hard Crust",
    "March Elegy",
    "Twenty-First. Night. Monday",
    "Memory of Sun",
    "Solitude",
    "I Taught Myself to Live Simply",
    "Crucifixion",
    "Crucifix",
],

"Wilfred Edward Salter Owen": [
    "Dulce et Decorum Est",
    "Dulce et Decorum est",
    "Anthem for Doomed Youth",
    "Strange Meeting",
    "Futility",
    "Spring Offensive",
    "Mental Cases",
    "Disabled",
    "The Send-Off",
    "Exposure",
    "Insensibility",
    "Arms and the Boy",
    "Greater Love",
    "Apologia pro Poemate Meo",
    "The Parable of the Old Man and the Young",
    "Parable of the Old Men and the Young",
    "Conscious",
    "The Rear-Guard",
],

"Edmund Spenser": [
    # Dataset stores the Amoretti as "Sonnet I*." "Sonnet II*." etc. (asterisked Roman numerals)
    "Sonnet I*.",
    "Sonnet II*.",
    "Sonnet III*.",
    "Sonnet IV*.",
    # Also include natural forms for any other Spenser poems
    "Prothalamion",
    "Epithalamion",
    "One Day I Wrote Her Name upon the Strand",
    "Muiopotmos",
    "An Hymne in Honour of Beautie",
    "An Hymne of Heavenly Beautie",
],

"Sophocles": [
    "Ode to Man",
    "Antigone: Ode to Man",
    "Chorus from Oedipus at Colonus",
],

"Geoffrey Chaucer": [
    "To My Empty Purse",
    "Complaint to His Purse",
    "Merciles Beaute",
    "To Rosemounde",
    "Truth",
    "Gentilesse",
    "Lack of Steadfastness",
    "The Former Age",
],

"Robert Herrick": [
    "To the Virgins, to Make Much of Time",
    "Corinna's Going a-Maying",
    "Delight in Disorder",
    "Upon Julia's Clothes",
    "The Night-Piece, to Julia",
    "Upon His Departure Hence",
    "To Daffodils",
    "A Thanksgiving to God, for His House",
    "His Prayer to Ben Jonson",
    "Cherry-Ripe",
    "To Anthea, Who May Command Him Anything",
    "The Mad Maid's Song",
    "The Primrose",
    "To Meadows",
    "Bid Me to Live",
    "The Hock-Cart, or Harvest Home",
    "Oberon's Feast",
    "The Argument of His Book",
    "Art above Nature, to Julia",
    "The Vine",
],

"Rudyard Kipling": [
    "If",
    "If—",
    "The Ballad of East and West",
    "Gunga Din",
    "The Road to Mandalay",
    "Recessional",
    "Tommy",
    "Danny Deever",
    "The White Man's Burden",
    "Mandalay",
    "Fuzzy-Wuzzy",
    "When Earth's Last Picture Is Painted",
    "Cities and Thrones and Powers",
    "Boots",
    "The Glory of the Garden",
    "Epitaphs of the War",
    "The Mary Gloster",
    "The Ladies",
    "The Return",
    "Great-Heart",
],

"Jonathan Swift": [
    "A Description of the Morning",
    "A Description of a City Shower",
    "The Lady's Dressing Room",
    "Verses on the Death of Dr. Swift",
    "A Beautiful Young Nymph Going to Bed",
    "Stella's Birthday",
    "The Progress of Beauty",
    "The Progress of Poetry",
    "On Poetry: A Rhapsody",
    "Journal of a Modern Lady",
    "To Stella, Who Collected and Transcribed His Poems",
],

"Edgar Lee Masters": [
    "Anne Rutledge",
    "Lucinda Matlock",
    "Petit, the Poet",
    "George Gray",
    "Fiddler Jones",
    "Daisy Fraser",
    "Benjamin Pantier",
    "Mrs. Benjamin Pantier",
    "Editor Whedon",
    "Harry Wilmans",
    "Carl Hamblin",
    "Hod Putt",
    "Seth Compton",
    "The Hill",
    "Doc Hill",
    "Barney Hainsfeather",
    "Aaron Hatfield",
    "Albert Schirding",
    "Trainor, the Druggist",
    "Hamilton Greene",
    "Theodore the Poet",
    "Jonathan Houghton",
    "Butch Weldy",
    "Davis Matlock",
    "Thomas Rhodes",
    "Reuben Pantier",
    "Russell Kincaid",
],

"Sara Teasdale": [
    "There Will Come Soft Rains",
    "Barter",
    "The Look",
    "Stars",
    "Spring Night",
    "Let It Be Forgotten",
    "The Kiss",
    "Spring",
    "August Night",
    "After Love",
    "Night Song at Amalfi",
    "The Answer",
    "I Am Not Yours",
    "Joy",
    "I Shall Not Care",
    "Places",
    "Dusk in June",
    "The Long Hill",
    "Effigy of a Nun",
    "Debt",
],

"Friedrich Schiller": [
    "Ode to Joy",
    "An die Freude",
    "The Diver",
    "The Glove",
    "The Pledge",
    "The Cranes of Ibykus",
    "The Ring of Polycrates",
    "Resignation",
    "The Gods of Greece",
    "The Song of the Bell",
    "Das Lied von der Glocke",
    "The Walk",
    "Ode to Joy (Beethoven)",
],

"Ralph Waldo Emerson": [
    "Concord Hymn",
    "The Rhodora",
    "Hamatreya",
    "Days",
    "Brahma",
    "Each and All",
    "The Sphinx",
    "Threnody",
    "Good-Bye",
    "The Problem",
    "Voluntaries",
    "Snow-Storm",
    "Uriel",
    "Ode to Beauty",
    "Merlin",
    "Woodnotes",
],

"D. H. Lawrence (David Herbert Richards)": [
    "Piano",
    "Snake",
    "Bavarian Gentians",
    "The Ship of Death",
    "Humming Bird",
    "Bat",
    "Fish",
    "Peach",
    "Green",
    "Love on the Farm",
    "The Bride",
    "Discord in Childhood",
    "End of Another Home Holiday",
    "Gloire de Dijon",
    "Cherry Robbers",
    "Song of a Man Who Has Come Through",
    "Tortoise Shell",
],

"Matthew Arnold": [
    "Dover Beach",
    "The Scholar-Gipsy",
    "Thyrsis",
    "Memorial Verses",
    "Stanzas from the Grande Chartreuse",
    "To Marguerite",
    "The Forsaken Merman",
    "Philomela",
    "Shakespeare",
    "The Buried Life",
    "Growing Old",
    "Resignation",
    "Rugby Chapel",
    "Isolation. To Marguerite",
    "A Summer Night",
    "Self-Dependence",
],

"Philip Sidney (Sir)": [
    "Loving in truth, and fain in verse my love to show",
    "Astrophil and Stella: Sonnet 1",
    "With how sad steps, O Moon",
    "Astrophil and Stella: Sonnet 31",
    "Come Sleep! O Sleep",
    "Astrophil and Stella: Sonnet 39",
    "My True Love Hath My Heart",
    "Ring Out Your Bells",
    "Ye Goatherd Gods",
    "A Ditty",
    "Leave Me, O Love",
    "Thou Blind Man's Mark",
    "What Length of Verse",
    "Astrophil and Stella: Sonnet 74",
],

"Gilbert Keith Chesterton": [
    "The Donkey",
    "Lepanto",
    "The Rolling English Road",
    "The Secret People",
    "A Hymn",
    "Wine and Water",
    "A Ballade of Suicide",
    "The House of Christmas",
    "For a War Memorial",
    "Antichrist, or the Reunion of Christendom",
    "The Convert",
    "Elegy in a Country Churchyard",
    "The Old Song",
],

"Robert von Ranke Graves": [
    "To Juan at the Winter Solstice",
    "The Cool Web",
    "Love Without Hope",
    "Lost Love",
    "Warning to Children",
    "Welsh Incident",
    "Counting the Beats",
    "The Persian Version",
    "The Legs",
    "She Tells Her Love While Half Asleep",
    "Recalling War",
    "Down, Wanton, Down!",
    "The Assault Heroic",
    "Rocky Acres",
    "A Pinch of Salt",
    "In Broken Images",
    "The White Goddess",
],

"Edna St. Vincent Millay": [
    "First Fig",
    "My candle burns at both ends",
    "Renascence",
    "Dirge Without Music",
    "What lips my lips have kissed",
    "The Buck in the Snow",
    "I Shall Forget You Presently",
    "Travel",
    "God's World",
    "Spring",
    "Afternoon on a Hill",
    "Love Is Not All",
    "Euclid Alone Has Looked on Beauty Bare",
    "Oh, Think Not I Am Faithful to a Vow",
    "Ashes of Life",
    "Bluebeard",
    "The Penitent",
    "Recuerdo",
    "Not in a Silver Casket",
],

"Edgar Allan Poe": [
    "The Raven",
    "Annabel Lee",
    "The Bells",
    "Ulalume",
    "El Dorado",
    "To Helen",
    "Lenore",
    "The Haunted Palace",
    "A Dream Within a Dream",
    "Alone",
    "The City in the Sea",
    "To One in Paradise",
    "For Annie",
    "Israfel",
    "Dreamland",
    "Romance",
    "Sonnet—To Science",
    "The Conqueror Worm",
    "Hymn",
],

"Emily Pauline Johnson": [
    "The Song My Paddle Sings",
    "The Cattle Thief",
    "As Red Men Die",
    "The Corn Husker",
    "Silhouette",
    "Shadow River",
    "The Idlers",
    "Canadian Born",
    "The Lost Lagoon",
    "Lullaby of the Iroquois",
    "At Husking Time",
    "The Riders of the Plains",
    "A Cry from an Indian Wife",
    "Wolverine",
    "Autumn's Orchestra",
],

"Siegfried Loraine Sassoon": [
    "Base Details",
    "The General",
    "Suicide in the Trenches",
    "Does It Matter?",
    "The Hero",
    "They",
    "Counter-Attack",
    "Aftermath",
    "Everyone Sang",
    "The Rear-Guard",
    "Attack",
    "Repression of War Experience",
    "The Kiss",
    "A Night Attack",
    "In the Pink",
    "Dreamers",
    "Prelude: The Troops",
    "October",
],

"Lewis Carroll": [
    "Jabberwocky",
    "The Walrus and the Carpenter",
    "You Are Old, Father William",
    "How Doth the Little Crocodile",
    "Beautiful Soup",
    "The Hunting of the Snark",
    "A Boat beneath a Sunny Sky",
    "The Mock Turtle's Song",
    "Speak Roughly to Your Little Boy",
    "The White Knight's Song",
    "Humpty Dumpty's Song",
    "Evidence Read at the Trial of the Knave of Hearts",
],

"Lola Ridge": [
    "The Ghetto",
    "Frank Little at Calvary",
    "Sun-Up",
    "The Legion of Iron",
    "Morning Ride",
    "The Alley",
    "Broadway",
    "Brooklyn Bridge",
    "Babel",
    "After Storm",
    "Altitude",
    "A Toast",
    "Manhattan",
    "Reveille",
    "Stone Face",
],

"Anne Bronte": [
    "The Prisoner",
    "The Doubter's Prayer",
    "Last Lines",
    "Memory",
    "Music on Christmas Morning",
    "The Parting",
    "The Captive Dove",
    "Home",
    "Views of Life",
    "A Fragment",
    "Call Me Away",
    "Self-Congratulation",
    "Vanitas Vanitatum",
    "The Consolation",
],

"Clark Ashton Smith": [
    "The Hashish-Eater",
    "Nero",
    "Atlantis",
    "Medusa",
    "Lethe",
    "A Dead City",
    "Chant to Sirius",
    "Finis",
    "Ode to the Abyss",
    "A Dream of Beauty",
    "Love Malevolent",
    "Averted Malefice",
    "In Lemuria",
    "Copan",
    "The Last Night",
    "Farewell to Eros",
],

"Frances Ellen Watkins Harper": [
    "Bury Me in a Free Land",
    "The Slave Mother",
    "Bible Defence of Slavery",
    "The Slave Auction",
    "Ethiopia",
    "An Appeal to the American People",
    "A Double Standard",
    "Learning to Read",
    "The Freedom Bell",
    "Save the Boys",
    "The Dying Christian",
    "The Contrast",
    "An Appeal to My Country Women",
    "Eliza Harris",
    "The Mother's Blessing",
],

"Yehuda Amichai": [
    "God Has Pity on Kindergarten Children",
    "A Man in His Life",
    "Jerusalem",
    "The Diameter of the Bomb",
    "My Father",
    "Tourists",
    "The Place Where We Are Right",
    "A Pity, We Were Such a Good Invention",
    "An Arab Shepherd Is Searching for His Goat on Mount Zion",
    "A Dog After Love",
    "A Man Doesn't Have Time in His Life",
    "National Thoughts",
    "Not the Peace of a Cease-Fire",
    "I Want to Die in My Bed",
    "Do Not Accept",
    "Forgetting Someone",
    "Mayor",
],

"Nizar Qabbani": [
    "Balqis",
    "Bread, Hashish and Moon",
    "Draw Me a Path",
    "When I Love You",
    "Jerusalem",
    "Marginal Notes on the Book of Defeat",
    "Letter from Under the Sea",
    "I Conquer the World with Words",
    "A Brief Love Letter",
    "A Damascene Moon",
    "Every Time I Kiss You",
    "Dialogue",
    "Language",
    "In the Summer",
    "The Actress",
    "Clarification to My Poetry-Readers",
    "Barada",
],

"Anne Bradstreet": [
    "To My Dear and Loving Husband",
    "Upon the Burning of Our House",
    "Contemplations",
    "A Letter to Her Husband, Absent upon Public Employment",
    "In Memory of My Dear Grandchild Elizabeth Bradstreet",
    "Before the Birth of One of Her Children",
    "The Author to Her Book",
    "The Flesh and the Spirit",
    "The Prologue",
    "In Honour of Du Bartas",
    "To Her Father with Some Verses",
    "The Vanity of All Worldly Things",
],

"John Wilmot": [
    "A Satyr Against Reason and Mankind",
    "The Imperfect Enjoyment",
    "The Disabled Debauchee",
    "Upon Nothing",
    "A Song",
    "Absent from Thee I Languish Still",
    "The Fall",
    "The Maim'd Debauchee",
    "Give Me Leave to Rail at You",
    "Love and Life",
    "My Dear Mistress Has a Heart",
],

"Thomas Carew": [
    "Ask Me No More",
    "An Elegy upon the Death of the Dean of Paul's",
    "Disdain Returned",
    "To My Inconstant Mistress",
    "Mediocrity in Love Rejected",
    "A Rapture",
    "Good Counsel to a Young Maid",
    "Epitaph on the Lady Mary Villiers",
    "To Saxham",
    "A Song",
    "A Song: Ask Me No More",
    "A Deposition from Love",
    "Boldness in Love",
    "A Cruel Mistress",
    "A Divine Mistress",
],

"Thomas Campion": [
    "There Is a Garden in Her Face",
    "Rose-Cheeked Laura",
    "My Sweetest Lesbia",
    "Follow Your Saint",
    "Cherry-Ripe",
    "I Care Not for These Ladies",
    "It Fell on a Summer's Day",
    "When to Her Lute Corinna Sings",
    "Never Weather-Beaten Sail",
    "Jack and Joan",
    "Now Winter Nights Enlarge",
    "What If a Day",
    "Thou Art Not Fair",
    "Turn All Thy Thoughts to Eyes",
],

"Aphra Behn": [
    "The Disappointment",
    "To the Fair Clarinda",
    "Love Armed",
    "Love in Fantastic Triumph Sat",
    "On a Juniper-Tree",
    "A Thousand Martyrs",
    "The Willing Mistress",
    "Song: Love in Fantastic Triumph Sat",
    "To Alexis in Answer to His Poem Against Fruition",
    "When Jemmy First Began to Love",
],

"Robert Lowell": [
    "Skunk Hour",
    "For the Union Dead",
    "The Quaker Graveyard in Nantucket",
    "Waking in the Blue",
    "Man and Wife",
    "Memories of West Street and Lepke",
    "Home After Three Months Away",
    "Grandparents",
    "Beyond the Alps",
    "My Last Afternoon with Uncle Devereux Winslow",
    "Sailing Home from Rapallo",
    "The Mouth of the Hudson",
    "Water",
    "For the Union Dead",
    "Walking Early Sunday Morning",
],

"Edwin Arlington Robinson": [
    "Richard Cory",
    "Miniver Cheevy",
    "Mr. Flood's Party",
    "Luke Havergal",
    "Eros Turannos",
    "The Mill",
    "For a Dead Lady",
    "Reuben Bright",
    "Aaron Stark",
    "Credo",
    "Two Men",
    "Cliff Klingenhagen",
    "John Evereldown",
    "Calverly's",
    "Fleming Helphenstine",
],

"Stephen Crane": [
    "In the desert",
    "I saw a creature, naked, bestial",
    "Do not weep, maiden, for war is kind",
    "A man said to the universe",
    "War is kind",
    "Black riders came from the sea",
    "I stood upon a high place",
    "A god in wrath",
    "The wayfarer",
    "In the Night",
    "Man, the",
    "Man, The",
    "Think as I think",
    "There was crimson clash of war",
],

"James Hogg": [
    "Kilmeny",
    "The Skylark",
    "When the Kye Comes Hame",
    "A Boy's Song",
    "Lock the Door, Lariston",
    "Bonnie Prince Charlie",
    "The Village of Balmaquapple",
],

"Richard Lovelace": [
    "To Althea, from Prison",
    "To Lucasta, Going to the Wars",
    "The Grasshopper",
    "To Amarantha, That She Would Dishevel Her Hair",
    "Song",
    "Gratiana Dancing and Singing",
    "La Bella Bona Roba",
    "Love Made in the First Age",
    "To Lucasta",
],

"Rupert Brooke": [
    "The Soldier",
    "The Old Vicarage, Grantchester",
    "Peace",
    "The Dead",
    "The Great Lover",
    "Menelaus and Helen",
    "Heaven",
    "Retrospect",
    "The Hill",
    "The Chilterns",
    "Beauty and Beauty",
    "Dead Men's Love",
    "Clouds",
    "A Channel Passage",
],

}

# ── sanity check ─────────────────────────────────────────────────────────────
print(f"Authors in canonical list : {len(CANONICAL)}")
for author, titles in CANONICAL.items():
    print(f"  {len(titles):>3}  {author}")

# ── save ─────────────────────────────────────────────────────────────────────
out_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'canonical_titles.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(CANONICAL, f, ensure_ascii=False, indent=2)
print(f"\nSaved → {out_path}")
